### ISSUE TITLE
Failed to update on windows 10

### ISSUE THREAD

**Issue by beat-juggler** [wendlers/atom-microbit-micropython#1]
serialport@4.0.7 install C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\node.exe C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport\build\Release --msvs_version=2015' (1)
C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh
`-- (empty)

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Program Files\Python35\python.EXE" is v3.5.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\jholt\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jholt\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\jholt\\AppData\\Local\\Temp\\apm-install-dir-117229-11796-1ybr1nh\\node_modules\\microbit-micropython\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\jholt\\AppData\\Local\\Temp\\apm-install-dir-117229-11796-1ybr1nh\\node_modules\\microbit-micropython\\node_modules\\serialport\\build\\Release" "--msvs_version=2015"
gyp ERR! cwd C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\node.exe C:\Users\jholt\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport\build\Release --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Users\\jholt\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jholt\\AppData\\Local\\Temp\\apm-install-dir-117229-11796-1ybr1nh\\node_modules\\microbit-micropython\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\node_modules\microbit-micropython\node_modules\serialport
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\package.json'
npm WARN apm-install-dir-117229-11796-1ybr1nh No description
npm WARN apm-install-dir-117229-11796-1ybr1nh No repository field.
npm WARN apm-install-dir-117229-11796-1ybr1nh No README data
npm WARN apm-install-dir-117229-11796-1ybr1nh No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\jholt\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jholt\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jholt\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jholt\\.atom\\.apmrc" "install" "C:\\Users\\jholt\\AppData\\Local\\Temp\\d-117229-11796-r1xmtv\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jholt\AppData\Local\Temp\apm-install-dir-117229-11796-1ybr1nh\npm-debug.log
npm ERR! code 1

**Comment by wendlers** [comment]
Hi, 
looks like the serialport npm package (which is now installed as a dependency) bugs out. However, the serialport package states it has Windows 10 support. I need to try on Win 10 but might take a little time (not using Win on my machines).

Other question: the version before worked for you on Win 10? Also the REPL worked?

Regards, 
Stefan

**Comment by wendlers** [comment]
Oh, and one other ting. Even if the updated would have worked, I think REPL and execution with the current version will not work on Windows. However, it would be good to support Windows too but ... well ... :-)

**Comment by beat-juggler** [comment]
Hi Stefan,

Thanks for the fast response. I have the previous version working but had
the problems when trying to upgrade.

Haven't tried the REPL so I'll give it a go and let you know.

Thanks
John

**Comment by wendlers** [comment]
Hi John,

I will try to check on this maybe on the weekend. Would be great if you could provide me the feedback on the REPL with Windows 10. 

Stefan

**Comment by wendlers** [comment]
Hi John,

I tired with Windows 10, and I get the same ERROR. It is caused by the "serialport" npm package. I also get the same error if I try to indipendently install "serialport" with npm. Actually I have no glue why this is caused (since the "serialport" package should support Windows). Currently I am thinking about to make that package an optional dependency to at least allow updates / installs on Windows too.

Regards, 
Stefan

**Comment by beat-juggler** [comment]
Hi Stefan,

Thanks for the update. I can't help test the REPL for you at the moment as
I uninstall the previous package and I can't install the new one.

Thanks
John

**Comment by mokytis** [comment]
I have the same issue in linux mint 18
