### ISSUE TITLE
Failed to load the microbit-micropython package

### ISSUE THREAD

**Issue by afreerunner** [wendlers/atom-microbit-micropython#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [microbit-micropython](https://github.com/wendlers/atom-microbit-micropython) package 0.2.0

### Stack Trace

Failed to load the microbit-micropython package

```
At Module version mismatch. Expected 49, got 48.

Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at bindings (/packages/microbit-micropython/node_modules/bindings/bindings.js:76:44)
    at /packages/microbit-micropython/node_modules/serialport/lib/bindings.js:3:35)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/microbit-micropython/node_modules/serialport/lib/serialport.js:12:25)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/microbit-micropython/lib/board.js:11:19)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-electron-snippets 2.0.3 
atom-live-server 2.1.2 
atom-nodejs-snippets 1.5.0 
atom-wx 0.1.1 
autocomplete-python 1.9.1 
autosave-onchange 1.5.1 
color-picker 2.2.5 
es6-javascript 1.0.0 
flask-snippets 0.3.3 
fonts-cjk 1.1.0 
javascript-snippets 1.2.1 
microbit-micropython 0.2.0 
node-debugger 1.10.1 
node-requirer 0.1.12 
python-indent 1.1.0 
python-run-terminalnx 1.0.3 
python-tools 0.6.9 
Remote-FTP 1.1.3 
```

**Comment by wendlers** [comment]
Hi, 
in the git repo, I updated one of the dependencies. I did not publish yet. Would you mind, trying the following and see if this helps with the issue?

In a shell:

```
# get repo
mkdir atom-mbtest
cd atom-mbtest
git clone https://github.com/wendlers/atom-microbit-micropython.git

# we use a fresh atom home for this test ...
mkdir atom
export ATOM_HOME=$PWD/atom

# start editor from that shell to set it up initially, then exit atom
atom

# install atom-microbit-micropython from repo
cd atom-microbit-micropython
apm link
apm install

# start atom to complete the setup
atom
```
I tried this with atom 1.18.0 on OpenSuse with success.
