### ISSUE TITLE
Failed to activate the microbit-micropython package

### ISSUE THREAD

**Issue by sauravyash** [wendlers/atom-microbit-micropython#5]
[Enter steps to reproduce:]

1. opening atom
2. that's it

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [microbit-micropython](https://github.com/wendlers/atom-microbit-micropython) package 0.3.2

### Stack Trace

Failed to activate the microbit-micropython package

```
At The module '/Users/Yash/.atom/packages/microbit-micropython/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/Users/Yash/.atom/packages/microbit-micropython/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at bindings (/packages/microbit-micropython/node_modules/bindings/bindings.js:76:44)
    at /packages/microbit-micropython/node_modules/serialport/lib/bindings.js:3:35)
    at /packages/microbit-micropython/node_modules/serialport/lib/bindings.js:36:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/microbit-micropython/node_modules/serialport/lib/serialport.js:12:25)
    at /packages/microbit-micropython/node_modules/serialport/lib/serialport.js:476:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/microbit-micropython/lib/board.js:11:19)
    at /packages/microbit-micropython/lib/board.js:13:27)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-ide-ui 0.13.0 
autocomplete-json 5.5.2 
autocomplete-python 1.14.0 
busy 0.7.0 
busy-signal 2.0.1 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
console-panel 0.3.1 
git-plus 8.6.2 
ide-rust 0.20.1 
intentions 1.1.5 
jsx-comment 0.2.0 
kite 0.170.0 
language-javascript-jsx 0.3.7 
language-json5 1.1.1 
language-pgsql 0.2.3 
language-rust 0.4.12 
linter 2.3.0 
linter-eslint 8.5.5 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
microbit-micropython 0.3.2 
pretty-json 2.1.2 
pug 0.8.0 
teletype 0.13.3 
terminal-plus 0.14.5 
termination 0.7.1 
tool-bar 1.1.11 
wakatime 7.0.9 
```

**Comment by monojk** [comment]
Is this still open? I get this failure in Atom.

**Comment by sauravyash** [comment]
> Is this still open? I get this failure in Atom.

It should be... 
I have disabled the package so im not up to date with whats happening though.
